--- # Poggit-CI Manifest. Open the CI at https://poggit.pmmp.io/ci/KTMGv5/RedBluePill
build-by-default: true
branches:
- main
projects:
  RedPillBluePill:
    path: RedBluePill/
    icon: icon.png
...
